/****************************************************************************
**
** Metadata for XGXLib generated by dumpcpp v5.13.1 using
** D:\software\qt_5_13_1\5.13.1\msvc2017_64\bin\dumpcpp.exe {241AC984-B8D3-4F78-B56F-B6B5268DF8F7}
** from the type library C:\Windows\SysWow64\XGXCTL.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_XGXLIB_NOINLINES
#include "xgxlib.h"

using namespace XGXLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[187];
    char stringdata0[2401];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 13, 0),
QT_MOC_LITERAL(1, 14, 9, 0),
QT_MOC_LITERAL(2, 24, 0, 0),
QT_MOC_LITERAL(3, 25, 4, 0),
QT_MOC_LITERAL(4, 30, 6, 0),
QT_MOC_LITERAL(5, 37, 4, 0),
QT_MOC_LITERAL(6, 42, 4, 0),
QT_MOC_LITERAL(7, 47, 15, 0),
QT_MOC_LITERAL(8, 63, 4, 0),
QT_MOC_LITERAL(9, 68, 6, 0),
QT_MOC_LITERAL(10, 75, 4, 0),
QT_MOC_LITERAL(11, 80, 4, 0),
QT_MOC_LITERAL(12, 85, 8, 0),
QT_MOC_LITERAL(13, 94, 20, 0),
QT_MOC_LITERAL(14, 115, 7, 0),
QT_MOC_LITERAL(15, 123, 18, 0),
QT_MOC_LITERAL(16, 142, 7, 0),
QT_MOC_LITERAL(17, 150, 10, 0),
QT_MOC_LITERAL(18, 161, 10, 0),
QT_MOC_LITERAL(19, 172, 14, 0),
QT_MOC_LITERAL(20, 187, 7, 0),
QT_MOC_LITERAL(21, 195, 9, 0),
QT_MOC_LITERAL(22, 205, 7, 0),
QT_MOC_LITERAL(23, 213, 18, 0),
QT_MOC_LITERAL(24, 232, 5, 0),
QT_MOC_LITERAL(25, 238, 19, 0),
QT_MOC_LITERAL(26, 258, 12, 0),
QT_MOC_LITERAL(27, 271, 7, 0),
QT_MOC_LITERAL(28, 279, 24, 0),
QT_MOC_LITERAL(29, 304, 22, 0),
QT_MOC_LITERAL(30, 327, 15, 0),
QT_MOC_LITERAL(31, 343, 14, 0),
QT_MOC_LITERAL(32, 358, 8, 0),
QT_MOC_LITERAL(33, 367, 16, 0),
QT_MOC_LITERAL(34, 384, 8, 0),
QT_MOC_LITERAL(35, 393, 7, 0),
QT_MOC_LITERAL(36, 401, 14, 0),
QT_MOC_LITERAL(37, 416, 7, 0),
QT_MOC_LITERAL(38, 424, 8, 0),
QT_MOC_LITERAL(39, 433, 8, 0),
QT_MOC_LITERAL(40, 442, 19, 0),
QT_MOC_LITERAL(41, 462, 17, 0),
QT_MOC_LITERAL(42, 480, 5, 0),
QT_MOC_LITERAL(43, 486, 4, 0),
QT_MOC_LITERAL(44, 491, 17, 0),
QT_MOC_LITERAL(45, 509, 3, 0),
QT_MOC_LITERAL(46, 513, 11, 0),
QT_MOC_LITERAL(47, 525, 4, 0),
QT_MOC_LITERAL(48, 530, 9, 0),
QT_MOC_LITERAL(49, 540, 10, 0),
QT_MOC_LITERAL(50, 551, 4, 0),
QT_MOC_LITERAL(51, 556, 4, 0),
QT_MOC_LITERAL(52, 561, 11, 0),
QT_MOC_LITERAL(53, 573, 6, 0),
QT_MOC_LITERAL(54, 580, 23, 0),
QT_MOC_LITERAL(55, 604, 15, 0),
QT_MOC_LITERAL(56, 620, 11, 0),
QT_MOC_LITERAL(57, 632, 8, 0),
QT_MOC_LITERAL(58, 641, 7, 0),
QT_MOC_LITERAL(59, 649, 6, 0),
QT_MOC_LITERAL(60, 656, 14, 0),
QT_MOC_LITERAL(61, 671, 12, 0),
QT_MOC_LITERAL(62, 684, 11, 0),
QT_MOC_LITERAL(63, 696, 14, 0),
QT_MOC_LITERAL(64, 711, 16, 0),
QT_MOC_LITERAL(65, 728, 14, 0),
QT_MOC_LITERAL(66, 743, 14, 0),
QT_MOC_LITERAL(67, 758, 13, 0),
QT_MOC_LITERAL(68, 772, 11, 0),
QT_MOC_LITERAL(69, 784, 10, 0),
QT_MOC_LITERAL(70, 795, 13, 0),
QT_MOC_LITERAL(71, 809, 9, 0),
QT_MOC_LITERAL(72, 819, 15, 0),
QT_MOC_LITERAL(73, 835, 15, 0),
QT_MOC_LITERAL(74, 851, 16, 0),
QT_MOC_LITERAL(75, 868, 6, 0),
QT_MOC_LITERAL(76, 875, 7, 0),
QT_MOC_LITERAL(77, 883, 8, 0),
QT_MOC_LITERAL(78, 892, 4, 0),
QT_MOC_LITERAL(79, 897, 7, 0),
QT_MOC_LITERAL(80, 905, 4, 0),
QT_MOC_LITERAL(81, 910, 10, 0),
QT_MOC_LITERAL(82, 921, 10, 0),
QT_MOC_LITERAL(83, 932, 7, 0),
QT_MOC_LITERAL(84, 940, 17, 0),
QT_MOC_LITERAL(85, 958, 14, 0),
QT_MOC_LITERAL(86, 973, 22, 0),
QT_MOC_LITERAL(87, 996, 19, 0),
QT_MOC_LITERAL(88, 1016, 7, 0),
QT_MOC_LITERAL(89, 1024, 4, 0),
QT_MOC_LITERAL(90, 1029, 16, 0),
QT_MOC_LITERAL(91, 1046, 13, 0),
QT_MOC_LITERAL(92, 1060, 16, 0),
QT_MOC_LITERAL(93, 1077, 13, 0),
QT_MOC_LITERAL(94, 1091, 16, 0),
QT_MOC_LITERAL(95, 1108, 13, 0),
QT_MOC_LITERAL(96, 1122, 16, 0),
QT_MOC_LITERAL(97, 1139, 13, 0),
QT_MOC_LITERAL(98, 1153, 16, 0),
QT_MOC_LITERAL(99, 1170, 13, 0),
QT_MOC_LITERAL(100, 1184, 16, 0),
QT_MOC_LITERAL(101, 1201, 13, 0),
QT_MOC_LITERAL(102, 1215, 16, 0),
QT_MOC_LITERAL(103, 1232, 13, 0),
QT_MOC_LITERAL(104, 1246, 16, 0),
QT_MOC_LITERAL(105, 1263, 13, 0),
QT_MOC_LITERAL(106, 1277, 16, 0),
QT_MOC_LITERAL(107, 1294, 13, 0),
QT_MOC_LITERAL(108, 1308, 13, 0),
QT_MOC_LITERAL(109, 1322, 10, 0),
QT_MOC_LITERAL(110, 1333, 13, 0),
QT_MOC_LITERAL(111, 1347, 10, 0),
QT_MOC_LITERAL(112, 1358, 13, 0),
QT_MOC_LITERAL(113, 1372, 10, 0),
QT_MOC_LITERAL(114, 1383, 13, 0),
QT_MOC_LITERAL(115, 1397, 10, 0),
QT_MOC_LITERAL(116, 1408, 13, 0),
QT_MOC_LITERAL(117, 1422, 10, 0),
QT_MOC_LITERAL(118, 1433, 13, 0),
QT_MOC_LITERAL(119, 1447, 10, 0),
QT_MOC_LITERAL(120, 1458, 13, 0),
QT_MOC_LITERAL(121, 1472, 10, 0),
QT_MOC_LITERAL(122, 1483, 13, 0),
QT_MOC_LITERAL(123, 1497, 10, 0),
QT_MOC_LITERAL(124, 1508, 13, 0),
QT_MOC_LITERAL(125, 1522, 10, 0),
QT_MOC_LITERAL(126, 1533, 16, 0),
QT_MOC_LITERAL(127, 1550, 6, 0),
QT_MOC_LITERAL(128, 1557, 15, 0),
QT_MOC_LITERAL(129, 1573, 13, 0),
QT_MOC_LITERAL(130, 1587, 18, 0),
QT_MOC_LITERAL(131, 1606, 4, 0),
QT_MOC_LITERAL(132, 1611, 14, 0),
QT_MOC_LITERAL(133, 1626, 14, 0),
QT_MOC_LITERAL(134, 1641, 12, 0),
QT_MOC_LITERAL(135, 1654, 17, 0),
QT_MOC_LITERAL(136, 1672, 13, 0),
QT_MOC_LITERAL(137, 1686, 19, 0),
QT_MOC_LITERAL(138, 1706, 12, 0),
QT_MOC_LITERAL(139, 1719, 7, 0),
QT_MOC_LITERAL(140, 1727, 16, 0),
QT_MOC_LITERAL(141, 1744, 17, 0),
QT_MOC_LITERAL(142, 1762, 10, 0),
QT_MOC_LITERAL(143, 1773, 22, 0),
QT_MOC_LITERAL(144, 1796, 20, 0),
QT_MOC_LITERAL(145, 1817, 13, 0),
QT_MOC_LITERAL(146, 1831, 13, 0),
QT_MOC_LITERAL(147, 1845, 12, 0),
QT_MOC_LITERAL(148, 1858, 14, 0),
QT_MOC_LITERAL(149, 1873, 11, 0),
QT_MOC_LITERAL(150, 1885, 9, 0),
QT_MOC_LITERAL(151, 1895, 16, 0),
QT_MOC_LITERAL(152, 1912, 17, 0),
QT_MOC_LITERAL(153, 1930, 19, 0),
QT_MOC_LITERAL(154, 1950, 15, 0),
QT_MOC_LITERAL(155, 1966, 20, 0),
QT_MOC_LITERAL(156, 1987, 16, 0),
QT_MOC_LITERAL(157, 2004, 19, 0),
QT_MOC_LITERAL(158, 2024, 7, 0),
QT_MOC_LITERAL(159, 2032, 7, 0),
QT_MOC_LITERAL(160, 2040, 11, 0),
QT_MOC_LITERAL(161, 2052, 17, 0),
QT_MOC_LITERAL(162, 2070, 11, 0),
QT_MOC_LITERAL(163, 2082, 5, 0),
QT_MOC_LITERAL(164, 2088, 8, 0),
QT_MOC_LITERAL(165, 2097, 7, 0),
QT_MOC_LITERAL(166, 2105, 7, 0),
QT_MOC_LITERAL(167, 2113, 5, 0),
QT_MOC_LITERAL(168, 2119, 5, 0),
QT_MOC_LITERAL(169, 2125, 9, 0),
QT_MOC_LITERAL(170, 2135, 6, 0),
QT_MOC_LITERAL(171, 2142, 1, 0),
QT_MOC_LITERAL(172, 2144, 1, 0),
QT_MOC_LITERAL(173, 2146, 9, 0),
QT_MOC_LITERAL(174, 2156, 7, 0),
QT_MOC_LITERAL(175, 2164, 17, 0),
QT_MOC_LITERAL(176, 2182, 5, 0),
QT_MOC_LITERAL(177, 2188, 17, 0),
QT_MOC_LITERAL(178, 2206, 24, 0),
QT_MOC_LITERAL(179, 2231, 19, 0),
QT_MOC_LITERAL(180, 2251, 20, 0),
QT_MOC_LITERAL(181, 2272, 22, 0),
QT_MOC_LITERAL(182, 2295, 17, 0),
QT_MOC_LITERAL(183, 2313, 22, 0),
QT_MOC_LITERAL(184, 2336, 23, 0),
QT_MOC_LITERAL(185, 2360, 18, 0),
QT_MOC_LITERAL(186, 2379, 20, 0)
    },
    "XGXLib::_DXGX\0exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0"
    "argc\0argv\0AboutBox\0CaptureRemoteDesktop\0dstFile\0ClearRemoteDesktop\0Connect\0"
    "DeleteFile\0Disconnect\0DownloadBinary\0driveNo\0settingNo\0dstPath\0DownloadDictionary\0"
    "dicNo\0DownloadEnvironment\0DownloadFile\0srcFile\0DownloadGlobalDictionary\0"
    "DownloadGlobalVariable\0DownloadInspect\0DownloadRecipe\0recipeNo\0DownloadRegImage\0"
    "cameraNo\0imageNo\0ExecuteCommand\0command\0QString&\0response\0ExecuteCommandAsync\0"
    "GetDictionaryInfo\0index\0int&\0GetDictionaryList\0num\0GetFileInfo\0kind\0attribute\0"
    "QDateTime&\0date\0size\0GetFileList\0folder\0GetGlobalDictionaryList\0GetHistoryImage\0"
    "conditionNo\0prcCount\0varName\0format\0GetHistoryInfo\0isSavedDrive\0isSavedComm\0"
    "GetHistoryList\0GetHistoryResult\0GetInspectInfo\0GetInspectList\0GetRecipeInfo\0"
    "recipeIndex\0recipeName\0GetRecipeList\0recipeNum\0GetRegImageInfo\0GetRegImageList\0"
    "GetResultLogData\0itemNo\0arrayNo\0memberNo\0text\0double&\0data\0Initialize\0"
    "SetAddress\0Address\0SetConnectionType\0ConnectionType\0SetEnableRemoteConsole\0"
    "EnableRemoteConsole\0SetPort\0Port\0SetRemoteJoypad0\0RemoteJoypad0\0SetRemoteJoypad1\0"
    "RemoteJoypad1\0SetRemoteJoypad2\0RemoteJoypad2\0SetRemoteJoypad3\0RemoteJoypad3\0"
    "SetRemoteJoypad4\0RemoteJoypad4\0SetRemoteJoypad5\0RemoteJoypad5\0SetRemoteJoypad6\0"
    "RemoteJoypad6\0SetRemoteJoypad7\0RemoteJoypad7\0SetRemoteJoypad8\0RemoteJoypad8\0"
    "SetRemoteKey0\0RemoteKey0\0SetRemoteKey1\0RemoteKey1\0SetRemoteKey2\0RemoteKey2\0"
    "SetRemoteKey3\0RemoteKey3\0SetRemoteKey4\0RemoteKey4\0SetRemoteKey5\0RemoteKey5\0"
    "SetRemoteKey6\0RemoteKey6\0SetRemoteKey7\0RemoteKey7\0SetRemoteKey8\0RemoteKey8\0"
    "SetResultLogUnit\0unitId\0StartHistoryLog\0StartImageLog\0StartRemoteDesktop\0"
    "mode\0StartResultLog\0StopHistoryLog\0StopImageLog\0StopRemoteDesktop\0StopResultLog\0"
    "UpdateRemoteDesktop\0UploadBinary\0srcPath\0UploadDictionary\0UploadEnvironment\0"
    "UploadFile\0UploadGlobalDictionary\0UploadGlobalVariable\0overwriteMode\0"
    "UploadInspect\0UploadRecipe\0UploadRegImage\0CommandBusy\0Connected\0FileTransferBusy\0"
    "HistoryLogStarted\0HistoryTransferBusy\0ImageLogStarted\0RemoteDesktopStarted\0"
    "ResultLogStarted\0SettingTransferBusy\0Version\0control\0XGXLib::XGX\0Event Interface 1\0"
    "_DXGXEvents\0Click\0DblClick\0KeyDown\0KeyCode\0Shift\0KeyUp\0MouseDown\0Button\0x\0y\0"
    "MouseMove\0MouseUp\0OnCommandFinished\0state\0OnFileTransferred\0OnHistoryLogDataReceived\0"
    "OnHistoryLogStopped\0OnHistoryTransferred\0OnImageLogDataReceived\0OnImageLogStopped\0"
    "OnRemoteDesktopUpdated\0OnResultLogDataReceived\0OnResultLogStopped\0"
    "OnSettingTransferred\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_XGXLib___DXGX[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    78, 14, // methods
    33, 772, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 404, 2, 5,
    7, 1, 413, 2, 5,
    9, 3, 416, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 423, 2, 9,
    13, 1, 424, 2, 9,
    15, 0, 427, 2, 9,
    16, 0, 428, 2, 9,
    17, 1, 429, 2, 9,
    18, 0, 432, 2, 9,
    19, 3, 433, 2, 9,
    23, 4, 440, 2, 9,
    25, 1, 449, 2, 9,
    26, 2, 452, 2, 9,
    28, 2, 457, 2, 9,
    29, 1, 462, 2, 9,
    30, 3, 465, 2, 9,
    31, 4, 472, 2, 9,
    33, 5, 481, 2, 9,
    36, 2, 492, 2, 9,
    40, 1, 497, 2, 9,
    41, 2, 500, 2, 9,
    44, 3, 505, 2, 9,
    46, 6, 512, 2, 9,
    52, 2, 525, 2, 9,
    54, 1, 530, 2, 9,
    55, 5, 533, 2, 9,
    60, 5, 544, 2, 9,
    63, 2, 555, 2, 9,
    64, 3, 560, 2, 9,
    65, 4, 567, 2, 9,
    66, 1, 576, 2, 9,
    67, 3, 579, 2, 9,
    70, 3, 586, 2, 9,
    72, 2, 593, 2, 9,
    73, 4, 598, 2, 9,
    74, 5, 607, 2, 9,
    81, 0, 618, 2, 9,
    82, 1, 619, 2, 9,
    84, 1, 622, 2, 9,
    86, 1, 625, 2, 9,
    88, 1, 628, 2, 9,
    90, 1, 631, 2, 9,
    92, 1, 634, 2, 9,
    94, 1, 637, 2, 9,
    96, 1, 640, 2, 9,
    98, 1, 643, 2, 9,
    100, 1, 646, 2, 9,
    102, 1, 649, 2, 9,
    104, 1, 652, 2, 9,
    106, 1, 655, 2, 9,
    108, 1, 658, 2, 9,
    110, 1, 661, 2, 9,
    112, 1, 664, 2, 9,
    114, 1, 667, 2, 9,
    116, 1, 670, 2, 9,
    118, 1, 673, 2, 9,
    120, 1, 676, 2, 9,
    122, 1, 679, 2, 9,
    124, 1, 682, 2, 9,
    126, 1, 685, 2, 9,
    128, 1, 688, 2, 9,
    129, 1, 691, 2, 9,
    130, 1, 694, 2, 9,
    132, 2, 697, 2, 9,
    133, 0, 702, 2, 9,
    134, 0, 703, 2, 9,
    135, 0, 704, 2, 9,
    136, 0, 705, 2, 9,
    137, 0, 706, 2, 9,
    138, 3, 707, 2, 9,
    140, 4, 714, 2, 9,
    141, 1, 723, 2, 9,
    142, 2, 726, 2, 9,
    143, 2, 731, 2, 9,
    144, 2, 736, 2, 9,
    146, 4, 741, 2, 9,
    147, 5, 750, 2, 9,
    148, 5, 761, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 22,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 24, 14,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 27, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::QString, 24, 14,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 32, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 34, 35, 14,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 38, 37, 39,
    QMetaType::Int, QMetaType::QString, 37,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 42, 24,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 20, 21, 45,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 38, 0x80000000 | 43, 0x80000000 | 43, 0x80000000 | 49, 0x80000000 | 43, 42, 8, 47, 48, 50, 51,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 43, 53, 45,
    QMetaType::Int, 0x80000000 | 43, 45,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::Int, 56, 57, 58, 14, 59,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 0x80000000 | 49, 0x80000000 | 43, 0x80000000 | 43, 42, 57, 50, 61, 62,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 56, 45,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 56, 57, 14,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 0x80000000 | 43, 0x80000000 | 38, 42, 20, 21, 8,
    QMetaType::Int, 0x80000000 | 43, 45,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 0x80000000 | 38, 68, 32, 69,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 20, 21, 71,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 42, 35,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 20, 21, 34, 45,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 38, 0x80000000 | 79, 75, 76, 77, 78, 80,
    QMetaType::Int,
    QMetaType::Void, QMetaType::QString, 83,
    QMetaType::Void, QMetaType::Int, 85,
    QMetaType::Void, QMetaType::Bool, 87,
    QMetaType::Void, QMetaType::Int, 89,
    QMetaType::Void, QMetaType::Int, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, QMetaType::Int, 99,
    QMetaType::Void, QMetaType::Int, 101,
    QMetaType::Void, QMetaType::Int, 103,
    QMetaType::Void, QMetaType::Int, 105,
    QMetaType::Void, QMetaType::Int, 107,
    QMetaType::Void, QMetaType::Int, 109,
    QMetaType::Void, QMetaType::Int, 111,
    QMetaType::Void, QMetaType::Int, 113,
    QMetaType::Void, QMetaType::Int, 115,
    QMetaType::Void, QMetaType::Int, 117,
    QMetaType::Void, QMetaType::Int, 119,
    QMetaType::Void, QMetaType::Int, 121,
    QMetaType::Void, QMetaType::Int, 123,
    QMetaType::Void, QMetaType::Int, 125,
    QMetaType::Int, QMetaType::Int, 127,
    QMetaType::Int, QMetaType::QString, 53,
    QMetaType::Int, QMetaType::QString, 53,
    QMetaType::Int, QMetaType::Int, 131,
    QMetaType::Int, QMetaType::Int, QMetaType::QString, 131, 53,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 139,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 24, 27,
    QMetaType::Int, QMetaType::QString, 27,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 27, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::QString, 24, 27,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 27, 145,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::Int, 20, 21, 27, 145,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::Int, 20, 21, 32, 27, 145,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 34, 35, 27,

 // properties: name, type, flags
    83, QMetaType::QString, 0x0a015003, 		 // QString Address
    149, QMetaType::Bool, 0x01005001, 		 // bool CommandBusy
    150, QMetaType::Bool, 0x01005001, 		 // bool Connected
    85, QMetaType::Int, 0x02015003, 		 // int ConnectionType
    87, QMetaType::Bool, 0x01015003, 		 // bool EnableRemoteConsole
    151, QMetaType::Bool, 0x01005001, 		 // bool FileTransferBusy
    152, QMetaType::Bool, 0x01005001, 		 // bool HistoryLogStarted
    153, QMetaType::Bool, 0x01005001, 		 // bool HistoryTransferBusy
    154, QMetaType::Bool, 0x01005001, 		 // bool ImageLogStarted
    89, QMetaType::Int, 0x02015003, 		 // int Port
    155, QMetaType::Bool, 0x01005001, 		 // bool RemoteDesktopStarted
    91, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad0
    93, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad1
    95, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad2
    97, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad3
    99, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad4
    101, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad5
    103, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad6
    105, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad7
    107, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad8
    109, QMetaType::Int, 0x02015003, 		 // int RemoteKey0
    111, QMetaType::Int, 0x02015003, 		 // int RemoteKey1
    113, QMetaType::Int, 0x02015003, 		 // int RemoteKey2
    115, QMetaType::Int, 0x02015003, 		 // int RemoteKey3
    117, QMetaType::Int, 0x02015003, 		 // int RemoteKey4
    119, QMetaType::Int, 0x02015003, 		 // int RemoteKey5
    121, QMetaType::Int, 0x02015003, 		 // int RemoteKey6
    123, QMetaType::Int, 0x02015003, 		 // int RemoteKey7
    125, QMetaType::Int, 0x02015003, 		 // int RemoteKey8
    156, QMetaType::Bool, 0x01005001, 		 // bool ResultLogStarted
    157, QMetaType::Bool, 0x01005001, 		 // bool SettingTransferBusy
    158, QMetaType::QString, 0x0a005001, 		 // QString Version
    159, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _DXGX::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_XGXLib___DXGX, 0, 0, 0 }
};

void *_DXGX::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "XGXLib::_DXGX"))
        return static_cast<void*>(const_cast<_DXGX*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_XGXLib__XGX[] = {

 // content:
    7, // revision
    160,  // classname
    1, 14, // classinfo
    96, 16, // methods
    32, 968, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    21, // signal count

 // classinfo: key, value
    161, 162, 

// signal: name, argc, parameters, tag, flags
    163, 0, 496, 2, 5,
    164, 0, 497, 2, 5,
    165, 2, 498, 2, 5,
    168, 2, 503, 2, 5,
    169, 4, 508, 2, 5,
    173, 4, 517, 2, 5,
    174, 4, 526, 2, 5,
    175, 2, 535, 2, 5,
    177, 2, 540, 2, 5,
    178, 5, 545, 2, 5,
    179, 1, 556, 2, 5,
    180, 2, 559, 2, 5,
    181, 5, 564, 2, 5,
    182, 1, 575, 2, 5,
    183, 1, 578, 2, 5,
    184, 5, 581, 2, 5,
    185, 1, 592, 2, 5,
    186, 2, 595, 2, 5,
    1, 4, 600, 2, 5,
    7, 1, 609, 2, 5,
    9, 3, 612, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 619, 2, 9,
    13, 1, 620, 2, 9,
    15, 0, 623, 2, 9,
    16, 0, 624, 2, 9,
    17, 1, 625, 2, 9,
    18, 0, 628, 2, 9,
    19, 3, 629, 2, 9,
    23, 4, 636, 2, 9,
    25, 1, 645, 2, 9,
    26, 2, 648, 2, 9,
    28, 2, 653, 2, 9,
    29, 1, 658, 2, 9,
    30, 3, 661, 2, 9,
    31, 4, 668, 2, 9,
    33, 5, 677, 2, 9,
    36, 2, 688, 2, 9,
    40, 1, 693, 2, 9,
    41, 2, 696, 2, 9,
    44, 3, 701, 2, 9,
    46, 6, 708, 2, 9,
    52, 2, 721, 2, 9,
    54, 1, 726, 2, 9,
    55, 5, 729, 2, 9,
    60, 5, 740, 2, 9,
    63, 2, 751, 2, 9,
    64, 3, 756, 2, 9,
    65, 4, 763, 2, 9,
    66, 1, 772, 2, 9,
    67, 3, 775, 2, 9,
    70, 3, 782, 2, 9,
    72, 2, 789, 2, 9,
    73, 4, 794, 2, 9,
    74, 5, 803, 2, 9,
    81, 0, 814, 2, 9,
    82, 1, 815, 2, 9,
    84, 1, 818, 2, 9,
    86, 1, 821, 2, 9,
    88, 1, 824, 2, 9,
    90, 1, 827, 2, 9,
    92, 1, 830, 2, 9,
    94, 1, 833, 2, 9,
    96, 1, 836, 2, 9,
    98, 1, 839, 2, 9,
    100, 1, 842, 2, 9,
    102, 1, 845, 2, 9,
    104, 1, 848, 2, 9,
    106, 1, 851, 2, 9,
    108, 1, 854, 2, 9,
    110, 1, 857, 2, 9,
    112, 1, 860, 2, 9,
    114, 1, 863, 2, 9,
    116, 1, 866, 2, 9,
    118, 1, 869, 2, 9,
    120, 1, 872, 2, 9,
    122, 1, 875, 2, 9,
    124, 1, 878, 2, 9,
    126, 1, 881, 2, 9,
    128, 1, 884, 2, 9,
    129, 1, 887, 2, 9,
    130, 1, 890, 2, 9,
    132, 2, 893, 2, 9,
    133, 0, 898, 2, 9,
    134, 0, 899, 2, 9,
    135, 0, 900, 2, 9,
    136, 0, 901, 2, 9,
    137, 0, 902, 2, 9,
    138, 3, 903, 2, 9,
    140, 4, 910, 2, 9,
    141, 1, 919, 2, 9,
    142, 2, 922, 2, 9,
    143, 2, 927, 2, 9,
    144, 2, 932, 2, 9,
    146, 4, 937, 2, 9,
    147, 5, 946, 2, 9,
    148, 5, 957, 2, 9,

// signal: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 43, QMetaType::Int, 166, 167,
    QMetaType::Void, 0x80000000 | 43, QMetaType::Int, 166, 167,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 170, 167, 171, 172,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 170, 167, 171, 172,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 170, 167, 171, 172,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 176, 37,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 176, 47,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 176, 20, 21, 56, 57,
    QMetaType::Void, QMetaType::Int, 176,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 176, 47,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 176, 20, 21, 127, 14,
    QMetaType::Void, QMetaType::Int, 176,
    QMetaType::Void, QMetaType::Int, 176,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 176, 20, 21, 127, 14,
    QMetaType::Void, QMetaType::Int, 176,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 176, 47,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 22,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 24, 14,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 27, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::QString, 24, 14,
    QMetaType::Int, QMetaType::QString, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 32, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 34, 35, 14,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 38, 37, 39,
    QMetaType::Int, QMetaType::QString, 37,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 42, 24,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 20, 21, 45,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 38, 0x80000000 | 43, 0x80000000 | 43, 0x80000000 | 49, 0x80000000 | 43, 42, 8, 47, 48, 50, 51,
    QMetaType::Int, QMetaType::QString, 0x80000000 | 43, 53, 45,
    QMetaType::Int, 0x80000000 | 43, 45,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::Int, 56, 57, 58, 14, 59,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 0x80000000 | 49, 0x80000000 | 43, 0x80000000 | 43, 42, 57, 50, 61, 62,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 56, 45,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 56, 57, 14,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 0x80000000 | 43, 0x80000000 | 38, 42, 20, 21, 8,
    QMetaType::Int, 0x80000000 | 43, 45,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 0x80000000 | 38, 68, 32, 69,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 20, 21, 71,
    QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 42, 35,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 43, 20, 21, 34, 45,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 38, 0x80000000 | 79, 75, 76, 77, 78, 80,
    QMetaType::Int,
    QMetaType::Void, QMetaType::QString, 83,
    QMetaType::Void, QMetaType::Int, 85,
    QMetaType::Void, QMetaType::Bool, 87,
    QMetaType::Void, QMetaType::Int, 89,
    QMetaType::Void, QMetaType::Int, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,
    QMetaType::Void, QMetaType::Int, 99,
    QMetaType::Void, QMetaType::Int, 101,
    QMetaType::Void, QMetaType::Int, 103,
    QMetaType::Void, QMetaType::Int, 105,
    QMetaType::Void, QMetaType::Int, 107,
    QMetaType::Void, QMetaType::Int, 109,
    QMetaType::Void, QMetaType::Int, 111,
    QMetaType::Void, QMetaType::Int, 113,
    QMetaType::Void, QMetaType::Int, 115,
    QMetaType::Void, QMetaType::Int, 117,
    QMetaType::Void, QMetaType::Int, 119,
    QMetaType::Void, QMetaType::Int, 121,
    QMetaType::Void, QMetaType::Int, 123,
    QMetaType::Void, QMetaType::Int, 125,
    QMetaType::Int, QMetaType::Int, 127,
    QMetaType::Int, QMetaType::QString, 53,
    QMetaType::Int, QMetaType::QString, 53,
    QMetaType::Int, QMetaType::Int, 131,
    QMetaType::Int, QMetaType::Int, QMetaType::QString, 131, 53,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 139,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 24, 27,
    QMetaType::Int, QMetaType::QString, 27,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 27, 14,
    QMetaType::Int, QMetaType::Int, QMetaType::QString, 24, 27,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 27, 145,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::Int, 20, 21, 27, 145,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, QMetaType::Int, 20, 21, 32, 27, 145,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QString, 20, 21, 34, 35, 27,

 // properties: name, type, flags
    83, QMetaType::QString, 0x0a015003, 		 // QString Address
    149, QMetaType::Bool, 0x01005001, 		 // bool CommandBusy
    150, QMetaType::Bool, 0x01005001, 		 // bool Connected
    85, QMetaType::Int, 0x02015003, 		 // int ConnectionType
    87, QMetaType::Bool, 0x01015003, 		 // bool EnableRemoteConsole
    151, QMetaType::Bool, 0x01005001, 		 // bool FileTransferBusy
    152, QMetaType::Bool, 0x01005001, 		 // bool HistoryLogStarted
    153, QMetaType::Bool, 0x01005001, 		 // bool HistoryTransferBusy
    154, QMetaType::Bool, 0x01005001, 		 // bool ImageLogStarted
    89, QMetaType::Int, 0x02015003, 		 // int Port
    155, QMetaType::Bool, 0x01005001, 		 // bool RemoteDesktopStarted
    91, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad0
    93, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad1
    95, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad2
    97, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad3
    99, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad4
    101, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad5
    103, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad6
    105, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad7
    107, QMetaType::Int, 0x02015003, 		 // int RemoteJoypad8
    109, QMetaType::Int, 0x02015003, 		 // int RemoteKey0
    111, QMetaType::Int, 0x02015003, 		 // int RemoteKey1
    113, QMetaType::Int, 0x02015003, 		 // int RemoteKey2
    115, QMetaType::Int, 0x02015003, 		 // int RemoteKey3
    117, QMetaType::Int, 0x02015003, 		 // int RemoteKey4
    119, QMetaType::Int, 0x02015003, 		 // int RemoteKey5
    121, QMetaType::Int, 0x02015003, 		 // int RemoteKey6
    123, QMetaType::Int, 0x02015003, 		 // int RemoteKey7
    125, QMetaType::Int, 0x02015003, 		 // int RemoteKey8
    156, QMetaType::Bool, 0x01005001, 		 // bool ResultLogStarted
    157, QMetaType::Bool, 0x01005001, 		 // bool SettingTransferBusy
    158, QMetaType::QString, 0x0a005001, 		 // QString Version

    0 // eod
};

const QMetaObject XGX::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_XGXLib__XGX, 0, 0, 0 }
};

void *XGX::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "XGXLib::XGX"))
        return static_cast<void*>(const_cast<XGX*>(this));
    return QAxWidget::qt_metacast(_clname);
}

