QWidget
    QAbstractButton
        QCheckBox
        QPushButton
            QCommandLinkButton
        QRadioButton
        QToolButton
    QAbstractSlider
        QDial
        QScrollBar
        QSlider
    QAbstractSpinBox
        QDateTimeEdit
            QDateEdit
            QTimeEdit
        QDoubleSpinBox
        QSpinBox
    QAxWidget
    QCalendarWidget
    QComboBox
        QFontComboBox
    QDesignerActionEditorInterface
    QDesignerFormWindowInterface
    QDesignerObjectInspectorInterface
    QDesignerPropertyEditorInterface
    QDesignerWidgetBoxInterface
    QDesktopWidget
    QDialog
        QAbstractPrintDialog
            QPrintDialog
        QAxSelect
        QColorDialog
        QErrorMessage
        QFileDialog
        QFontDialog
        QInputDialog
        QMessageBox
        QPageSetupDialog
        QPrintPreviewDialog
        QProgressDialog
        QWizard
    QDialogButtonBox
    QDockWidget
    QFocusFrame
    QFrame
        QAbstractScrollArea
            QAbstractItemView
                QColumnView
                QHeaderView
                QListView
                    QHelpIndexWidget
                    QListWidget
                    QUndoView
                QTableView
                    QTableWidget
                QTreeView
                    QHelpContentWidget
                    QTreeWidget
            QGraphicsView
                QChartView
            QMdiArea
            QPlainTextEdit
            QScrollArea
            QTextEdit
                QTextBrowser
        QLCDNumber
        QLabel
        QSplitter
        QStackedWidget
        QToolBox
    QGLWidget
    QGroupBox
    QHelpFilterSettingsWidget
    QHelpSearchQueryWidget
    QHelpSearchResultWidget
    QKeySequenceEdit
    QLineEdit
    QMacCocoaViewContainer
    QMacNativeWidget
    QMainWindow
    QMdiSubWindow
    QMenu
    QMenuBar
    QOpenGLWidget
    QPrintPreviewWidget
    QProgressBar
    QQuickWidget
    QRubberBand
    QSizeGrip
    QSplashScreen
    QSplitterHandle
    QStatusBar
    QSvgWidget
    QTabBar
    QTabWidget
    QToolBar
    QVideoWidget
    QWebEngineView
    QWizardPage
